services:
  ff2_telegram_ui:
    container_name: ff2_telegram_ui
    env_file:
      - .env
    build:
      context: .
    volumes:
      - ff2_telegram_ui_logs:/app/src/logs
    restart: always

volumes:
  ff2_telegram_ui_logs:
