name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REPO: ivanovdv/ff2-telegram-ui

jobs:
  flake8 and pytest:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.8.4
    - name: Install dependencies
      run: poetry install --with dev
    - name: Flake8
      run: |
        poetry run flake8 src/
        poetry run pytest

  deploy_via_k8s:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_REPO:latest .
          docker push $DOCKER_REPO:latest

      - name: Set up kubectl and deploy
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl version --client
          kubectl apply -f k8s/
          kubectl rollout restart deployment ff2-telegram-ui
